/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FramesCarmarero;

import java.awt.BorderLayout;

/**
 *
 * @author Manu
 */
public class PanelNotificaciones extends javax.swing.JPanel {

    /**
     * Creates new form PanelNotificaciones
     */
    public PanelNotificaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        botonVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelScroll = new javax.swing.JPanel();
        PMesa1 = new javax.swing.JPanel();
        labelTituloNotificaion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botonDespachar1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        PMesa2 = new javax.swing.JPanel();
        labelTituloNotificaion1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        botonDespachar2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        PMesa3 = new javax.swing.JPanel();
        labelTituloNotificaion2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        botonDespachar3 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1080, 720));
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setLayout(null);

        labelTitulo.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        labelTitulo.setText("Notificaciones");
        add(labelTitulo);
        labelTitulo.setBounds(418, 30, 212, 42);

        botonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FramesCliente/imagenes/Volver.png"))); // NOI18N
        botonVolver.setMaximumSize(new java.awt.Dimension(100, 75));
        botonVolver.setMinimumSize(new java.awt.Dimension(100, 75));
        botonVolver.setPreferredSize(new java.awt.Dimension(100, 75));
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        add(botonVolver);
        botonVolver.setBounds(32, 577, 100, 75);

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(32767, 2000));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(23, 2000));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(100, 2000));

        panelScroll.setMaximumSize(new java.awt.Dimension(660, 1000));
        panelScroll.setMinimumSize(new java.awt.Dimension(660, 1000));
        panelScroll.setPreferredSize(new java.awt.Dimension(660, 1000));

        PMesa1.setMaximumSize(new java.awt.Dimension(570, 240));
        PMesa1.setMinimumSize(new java.awt.Dimension(570, 240));
        PMesa1.setPreferredSize(new java.awt.Dimension(570, 631));

        labelTituloNotificaion.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labelTituloNotificaion.setText("Notificación bebida");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FramesCliente/imagenes/AlertasCubiertosVasos/imagenVaso.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Mesa:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Cliente:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Bebida:");

        botonDespachar1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonDespachar1.setText("Despachar");
        botonDespachar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDespachar1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("1");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("3");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Coca - Cola");

        javax.swing.GroupLayout PMesa1Layout = new javax.swing.GroupLayout(PMesa1);
        PMesa1.setLayout(PMesa1Layout);
        PMesa1Layout.setHorizontalGroup(
            PMesa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PMesa1Layout.createSequentialGroup()
                .addGroup(PMesa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PMesa1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(labelTituloNotificaion))
                    .addGroup(PMesa1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(PMesa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PMesa1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5))
                            .addGroup(PMesa1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))
                            .addGroup(PMesa1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PMesa1Layout.createSequentialGroup()
                .addGap(0, 190, Short.MAX_VALUE)
                .addComponent(botonDespachar1)
                .addGap(185, 185, 185))
        );
        PMesa1Layout.setVerticalGroup(
            PMesa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PMesa1Layout.createSequentialGroup()
                .addGroup(PMesa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PMesa1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(labelTituloNotificaion)
                        .addGap(18, 18, 18)
                        .addGroup(PMesa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)))
                    .addGroup(PMesa1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PMesa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(PMesa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(botonDespachar1)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        PMesa2.setMaximumSize(new java.awt.Dimension(570, 240));
        PMesa2.setMinimumSize(new java.awt.Dimension(570, 240));
        PMesa2.setPreferredSize(new java.awt.Dimension(570, 631));

        labelTituloNotificaion1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labelTituloNotificaion1.setText("Notificación pagar");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FramesCarmarero/imagenes/imagenPagar.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Mesa:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Cliente:");

        botonDespachar2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonDespachar2.setText("Despachar");
        botonDespachar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDespachar2ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("4");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("3");

        javax.swing.GroupLayout PMesa2Layout = new javax.swing.GroupLayout(PMesa2);
        PMesa2.setLayout(PMesa2Layout);
        PMesa2Layout.setHorizontalGroup(
            PMesa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PMesa2Layout.createSequentialGroup()
                .addGroup(PMesa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PMesa2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(labelTituloNotificaion1))
                    .addGroup(PMesa2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(PMesa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PMesa2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12))
                            .addGroup(PMesa2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 240, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
            .addGroup(PMesa2Layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(botonDespachar2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PMesa2Layout.setVerticalGroup(
            PMesa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PMesa2Layout.createSequentialGroup()
                .addGroup(PMesa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PMesa2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(labelTituloNotificaion1)
                        .addGap(18, 18, 18)
                        .addGroup(PMesa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12)))
                    .addGroup(PMesa2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PMesa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addComponent(botonDespachar2)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        PMesa3.setMaximumSize(new java.awt.Dimension(570, 240));
        PMesa3.setMinimumSize(new java.awt.Dimension(570, 240));
        PMesa3.setPreferredSize(new java.awt.Dimension(570, 631));

        labelTituloNotificaion2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labelTituloNotificaion2.setText("Notificación siguiente plato");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FramesCarmarero/imagenes/imagenPlato.png"))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setText("Mesa:");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setText("Cliente:");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setText("Plato:");

        botonDespachar3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonDespachar3.setText("Despachar");
        botonDespachar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDespachar3ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setText("4");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel21.setText("2");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel22.setText("Postre");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel23.setText("NombrePostre");

        javax.swing.GroupLayout PMesa3Layout = new javax.swing.GroupLayout(PMesa3);
        PMesa3.setLayout(PMesa3Layout);
        PMesa3Layout.setHorizontalGroup(
            PMesa3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PMesa3Layout.createSequentialGroup()
                .addGroup(PMesa3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PMesa3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(labelTituloNotificaion2))
                    .addGroup(PMesa3Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(PMesa3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PMesa3Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel20))
                            .addGroup(PMesa3Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel21))
                            .addGroup(PMesa3Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel22)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel23)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PMesa3Layout.createSequentialGroup()
                .addGap(0, 190, Short.MAX_VALUE)
                .addComponent(botonDespachar3)
                .addGap(185, 185, 185))
        );
        PMesa3Layout.setVerticalGroup(
            PMesa3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PMesa3Layout.createSequentialGroup()
                .addGroup(PMesa3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PMesa3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(labelTituloNotificaion2)
                        .addGap(18, 18, 18)
                        .addGroup(PMesa3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel20)))
                    .addGroup(PMesa3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PMesa3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(PMesa3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addComponent(botonDespachar3)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelScrollLayout = new javax.swing.GroupLayout(panelScroll);
        panelScroll.setLayout(panelScrollLayout);
        panelScrollLayout.setHorizontalGroup(
            panelScrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelScrollLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panelScrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PMesa3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PMesa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PMesa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(388, Short.MAX_VALUE))
        );
        panelScrollLayout.setVerticalGroup(
            panelScrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelScrollLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(PMesa1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(PMesa3, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(PMesa2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(panelScroll);

        add(jScrollPane1);
        jScrollPane1.setBounds(32, 90, 1017, 476);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FramesCarmarero/imagenes/fondoCamareros 2.png"))); // NOI18N
        add(jLabel11);
        jLabel11.setBounds(0, 0, 1080, 720);
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        // TODO add your handling code here:
        PanelEstadoRestaurante p = new PanelEstadoRestaurante();
        p.setSize(1080, 720);
        p.setLocation(0, 0);

        this.removeAll();
        this.add(p, BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonDespachar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDespachar1ActionPerformed
        // TODO add your handling code here:
        PMesa1.removeAll();
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_botonDespachar1ActionPerformed

    private void botonDespachar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDespachar3ActionPerformed
        // TODO add your handling code here:
        PMesa3.removeAll();
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_botonDespachar3ActionPerformed

    private void botonDespachar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDespachar2ActionPerformed
        // TODO add your handling code here:
        PMesa2.removeAll();
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_botonDespachar2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PMesa1;
    private javax.swing.JPanel PMesa2;
    private javax.swing.JPanel PMesa3;
    private javax.swing.JButton botonDespachar1;
    private javax.swing.JButton botonDespachar2;
    private javax.swing.JButton botonDespachar3;
    private javax.swing.JButton botonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelTituloNotificaion;
    private javax.swing.JLabel labelTituloNotificaion1;
    private javax.swing.JLabel labelTituloNotificaion2;
    private javax.swing.JPanel panelScroll;
    // End of variables declaration//GEN-END:variables
}
