/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FramesCarmarero;

import java.awt.BorderLayout;

/**
 *
 * @author Manu
 */
public class PanelEstadoRestaurante extends javax.swing.JPanel {

    /**
     * Creates new form PanelEstadoRestaurante
     */
    public PanelEstadoRestaurante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonOcupacionMesas = new javax.swing.JButton();
        botonPanelPedidos = new javax.swing.JButton();
        botonNotificaciones = new javax.swing.JButton();
        labelNumeroNotificaciones = new javax.swing.JLabel();
        botonVolver = new javax.swing.JButton();
        imagenOcupacionMesas = new javax.swing.JLabel();
        imagenPedidos = new javax.swing.JLabel();
        imagenNotificaciones = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1080, 720));
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setPreferredSize(new java.awt.Dimension(1080, 720));
        setLayout(null);

        botonOcupacionMesas.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonOcupacionMesas.setText("Ocupación de las mesas");
        botonOcupacionMesas.setMaximumSize(new java.awt.Dimension(550, 150));
        botonOcupacionMesas.setMinimumSize(new java.awt.Dimension(550, 150));
        botonOcupacionMesas.setPreferredSize(new java.awt.Dimension(550, 150));
        botonOcupacionMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOcupacionMesasActionPerformed(evt);
            }
        });
        add(botonOcupacionMesas);
        botonOcupacionMesas.setBounds(368, 69, 550, 150);

        botonPanelPedidos.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonPanelPedidos.setText("Pedidos");
        botonPanelPedidos.setMaximumSize(new java.awt.Dimension(550, 150));
        botonPanelPedidos.setMinimumSize(new java.awt.Dimension(550, 150));
        botonPanelPedidos.setPreferredSize(new java.awt.Dimension(550, 150));
        botonPanelPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPanelPedidosActionPerformed(evt);
            }
        });
        add(botonPanelPedidos);
        botonPanelPedidos.setBounds(368, 286, 550, 150);

        botonNotificaciones.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonNotificaciones.setText("Notificaciones");
        botonNotificaciones.setMaximumSize(new java.awt.Dimension(550, 150));
        botonNotificaciones.setMinimumSize(new java.awt.Dimension(550, 150));
        botonNotificaciones.setPreferredSize(new java.awt.Dimension(550, 150));
        botonNotificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNotificacionesActionPerformed(evt);
            }
        });
        add(botonNotificaciones);
        botonNotificaciones.setBounds(368, 503, 550, 150);

        labelNumeroNotificaciones.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        labelNumeroNotificaciones.setForeground(new java.awt.Color(255, 0, 0));
        labelNumeroNotificaciones.setText("!");
        add(labelNumeroNotificaciones);
        labelNumeroNotificaciones.setBounds(936, 503, 16, 56);

        botonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FramesCliente/imagenes/Volver.png"))); // NOI18N
        botonVolver.setMaximumSize(new java.awt.Dimension(100, 75));
        botonVolver.setMinimumSize(new java.awt.Dimension(100, 75));
        botonVolver.setPreferredSize(new java.awt.Dimension(100, 75));
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        add(botonVolver);
        botonVolver.setBounds(30, 578, 100, 75);

        imagenOcupacionMesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FramesCarmarero/imagenes/icons8-table-100.png"))); // NOI18N
        add(imagenOcupacionMesas);
        imagenOcupacionMesas.setBounds(208, 99, 100, 100);

        imagenPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FramesCliente/imagenes/imagenPedido.png"))); // NOI18N
        add(imagenPedidos);
        imagenPedidos.setBounds(208, 309, 100, 100);

        imagenNotificaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FramesCarmarero/imagenes/imagenNotificaciones.png"))); // NOI18N
        add(imagenNotificaciones);
        imagenNotificaciones.setBounds(208, 517, 100, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FramesCarmarero/imagenes/fondoCamareros 2.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1080, 720);
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        // TODO add your handling code here:
        PanelMenuCamarero p = new PanelMenuCamarero();
	p.setSize(1080, 720);
	p.setLocation(0, 0);
		
	this.removeAll();
	this.add(p, BorderLayout.CENTER);
	this.revalidate();
	this.repaint();
    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonOcupacionMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOcupacionMesasActionPerformed
        // TODO add your handling code here:
        PanelOcupacionMesas p = new PanelOcupacionMesas();
	p.setSize(1080, 720);
	p.setLocation(0, 0);
		
	this.removeAll();
	this.add(p, BorderLayout.CENTER);
	this.revalidate();
	this.repaint();
    }//GEN-LAST:event_botonOcupacionMesasActionPerformed

    private void botonPanelPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPanelPedidosActionPerformed
        // TODO add your handling code here:
        PanelPedidos p = new PanelPedidos();
	p.setSize(1080, 720);
	p.setLocation(0, 0);
		
	this.removeAll();
	this.add(p, BorderLayout.CENTER);
	this.revalidate();
	this.repaint();
    }//GEN-LAST:event_botonPanelPedidosActionPerformed

    private void botonNotificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNotificacionesActionPerformed
        // TODO add your handling code here:
        PanelNotificaciones p = new PanelNotificaciones();
	p.setSize(1080, 720);
	p.setLocation(0, 0);
		
	this.removeAll();
	this.add(p, BorderLayout.CENTER);
	this.revalidate();
	this.repaint();
    }//GEN-LAST:event_botonNotificacionesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonNotificaciones;
    private javax.swing.JButton botonOcupacionMesas;
    private javax.swing.JButton botonPanelPedidos;
    private javax.swing.JButton botonVolver;
    private javax.swing.JLabel imagenNotificaciones;
    private javax.swing.JLabel imagenOcupacionMesas;
    private javax.swing.JLabel imagenPedidos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelNumeroNotificaciones;
    // End of variables declaration//GEN-END:variables
}
