/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FramesCarmarero;

import java.awt.BorderLayout;

/**
 *
 * @author Manu
 */
public class PanelOcupacionMesas extends javax.swing.JPanel {

    /**
     * Creates new form panelOcupacionMesas
     */
    public PanelOcupacionMesas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelScroll = new javax.swing.JPanel();
        PMesa1 = new javax.swing.JPanel();
        Mesa1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        PMesa2 = new javax.swing.JPanel();
        Mesa2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        PMesa3 = new javax.swing.JPanel();
        Mesa3 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        PMesa4 = new javax.swing.JPanel();
        Mesa4 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        botonVolver = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1080, 720));
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setLayout(null);

        labelTitulo.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        labelTitulo.setText("Ocupación de las mesas");
        add(labelTitulo);
        labelTitulo.setBounds(348, 28, 358, 42);

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(32767, 1075));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(23, 1075));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(100, 1075));

        panelScroll.setMaximumSize(new java.awt.Dimension(660, 1075));
        panelScroll.setMinimumSize(new java.awt.Dimension(660, 1075));
        panelScroll.setPreferredSize(new java.awt.Dimension(660, 1075));
        panelScroll.setLayout(null);

        PMesa1.setMaximumSize(new java.awt.Dimension(570, 240));
        PMesa1.setMinimumSize(new java.awt.Dimension(570, 240));
        PMesa1.setPreferredSize(new java.awt.Dimension(570, 240));

        Mesa1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Mesa1.setText("Mesa 1:");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Estado de la mesa :");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Plato del comensal:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Comensal 1:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Comensal 2:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Comensal 3:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Ocupado");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Primer plato");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Primer plato");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Primer plato");

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FramesCarmarero/imagenes/imagenOcupado.png"))); // NOI18N

        javax.swing.GroupLayout PMesa1Layout = new javax.swing.GroupLayout(PMesa1);
        PMesa1.setLayout(PMesa1Layout);
        PMesa1Layout.setHorizontalGroup(
            PMesa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PMesa1Layout.createSequentialGroup()
                .addGroup(PMesa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PMesa1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Mesa1))
                    .addGroup(PMesa1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(PMesa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(PMesa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(25, 25, 25)
                        .addGroup(PMesa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PMesa1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel35))
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        PMesa1Layout.setVerticalGroup(
            PMesa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PMesa1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Mesa1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PMesa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PMesa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel6))
                    .addComponent(jLabel35))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(PMesa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(PMesa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(PMesa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        panelScroll.add(PMesa1);
        PMesa1.setBounds(40, 40, 570, 240);

        PMesa2.setMaximumSize(new java.awt.Dimension(570, 240));
        PMesa2.setMinimumSize(new java.awt.Dimension(570, 240));
        PMesa2.setPreferredSize(new java.awt.Dimension(570, 240));

        Mesa2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Mesa2.setText("Mesa 2:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Estado de la mesa :");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Plato del comensal:");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Comensal 1:");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("Comensal 2:");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("Comensal 3:");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("Ocupado");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("Primer plato");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setText("Segundo plato");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setText("Segundo plato");

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FramesCarmarero/imagenes/imagenOcupado.png"))); // NOI18N

        javax.swing.GroupLayout PMesa2Layout = new javax.swing.GroupLayout(PMesa2);
        PMesa2.setLayout(PMesa2Layout);
        PMesa2Layout.setHorizontalGroup(
            PMesa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PMesa2Layout.createSequentialGroup()
                .addGroup(PMesa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PMesa2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Mesa2))
                    .addGroup(PMesa2Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(PMesa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addGroup(PMesa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel10))
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(25, 25, 25)
                        .addGroup(PMesa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PMesa2Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel33))
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        PMesa2Layout.setVerticalGroup(
            PMesa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PMesa2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Mesa2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PMesa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel15)
                    .addComponent(jLabel33))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(PMesa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(PMesa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(PMesa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel18))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        panelScroll.add(PMesa2);
        PMesa2.setBounds(40, 320, 570, 240);

        PMesa3.setMaximumSize(new java.awt.Dimension(570, 125));
        PMesa3.setMinimumSize(new java.awt.Dimension(570, 125));
        PMesa3.setPreferredSize(new java.awt.Dimension(570, 125));

        Mesa3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Mesa3.setText("Mesa 3:");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setText("Estado de la mesa :");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setText("Plato del comensal:");

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel24.setText("Libre");

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FramesCarmarero/imagenes/imagenLibre.png"))); // NOI18N

        javax.swing.GroupLayout PMesa3Layout = new javax.swing.GroupLayout(PMesa3);
        PMesa3.setLayout(PMesa3Layout);
        PMesa3Layout.setHorizontalGroup(
            PMesa3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PMesa3Layout.createSequentialGroup()
                .addGroup(PMesa3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PMesa3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Mesa3))
                    .addGroup(PMesa3Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(PMesa3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19))
                        .addGap(25, 25, 25)
                        .addComponent(jLabel24)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel34)))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        PMesa3Layout.setVerticalGroup(
            PMesa3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PMesa3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Mesa3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PMesa3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel24)
                    .addComponent(jLabel34))
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelScroll.add(PMesa3);
        PMesa3.setBounds(40, 600, 570, 125);

        PMesa4.setMaximumSize(new java.awt.Dimension(570, 240));
        PMesa4.setMinimumSize(new java.awt.Dimension(570, 240));

        Mesa4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Mesa4.setText("Mesa 4:");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel21.setText("Estado de la mesa :");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel22.setText("Plato del comensal:");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel23.setText("Comensal 1:");

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel25.setText("Comensal 2:");

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel26.setText("Comensal 3:");

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel27.setText("Ocupado");

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel28.setText("Postre");

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel29.setText("Segundo plato");

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel30.setText("Segundo plato");

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel31.setText("Comensal 4:");

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel32.setText("Segundo plato");

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FramesCarmarero/imagenes/imagenOcupado.png"))); // NOI18N

        javax.swing.GroupLayout PMesa4Layout = new javax.swing.GroupLayout(PMesa4);
        PMesa4.setLayout(PMesa4Layout);
        PMesa4Layout.setHorizontalGroup(
            PMesa4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PMesa4Layout.createSequentialGroup()
                .addGroup(PMesa4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PMesa4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Mesa4))
                    .addGroup(PMesa4Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(PMesa4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23)
                            .addGroup(PMesa4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel22)
                                .addComponent(jLabel21))
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel31))
                        .addGap(25, 25, 25)
                        .addGroup(PMesa4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PMesa4Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel36))
                            .addComponent(jLabel28)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30)
                            .addComponent(jLabel32))))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        PMesa4Layout.setVerticalGroup(
            PMesa4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PMesa4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Mesa4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PMesa4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PMesa4Layout.createSequentialGroup()
                        .addGroup(PMesa4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel27))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel22))
                    .addComponent(jLabel36))
                .addGap(18, 18, 18)
                .addGroup(PMesa4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel28))
                .addGap(18, 18, 18)
                .addGroup(PMesa4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel29))
                .addGap(18, 18, 18)
                .addGroup(PMesa4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel30))
                .addGap(18, 18, 18)
                .addGroup(PMesa4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        panelScroll.add(PMesa4);
        PMesa4.setBounds(40, 765, 579, 277);

        jScrollPane1.setViewportView(panelScroll);

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 106, 1017, 476);

        botonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FramesCliente/imagenes/Volver.png"))); // NOI18N
        botonVolver.setMaximumSize(new java.awt.Dimension(100, 75));
        botonVolver.setMinimumSize(new java.awt.Dimension(100, 75));
        botonVolver.setPreferredSize(new java.awt.Dimension(100, 75));
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        add(botonVolver);
        botonVolver.setBounds(30, 593, 100, 75);

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FramesCarmarero/imagenes/fondoCamareros 2.png"))); // NOI18N
        add(jLabel37);
        jLabel37.setBounds(0, 0, 1080, 720);
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        // TODO add your handling code here:
        PanelEstadoRestaurante p = new PanelEstadoRestaurante();
	p.setSize(1080, 720);
	p.setLocation(0, 0);
		
	this.removeAll();
	this.add(p, BorderLayout.CENTER);
	this.revalidate();
	this.repaint();
    }//GEN-LAST:event_botonVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Mesa1;
    private javax.swing.JLabel Mesa2;
    private javax.swing.JLabel Mesa3;
    private javax.swing.JLabel Mesa4;
    private javax.swing.JPanel PMesa1;
    private javax.swing.JPanel PMesa2;
    private javax.swing.JPanel PMesa3;
    private javax.swing.JPanel PMesa4;
    private javax.swing.JButton botonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelScroll;
    // End of variables declaration//GEN-END:variables
}
