/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FramesCliente;

import java.awt.BorderLayout;

/**
 *
 * @author Alber
 */
public class PanelInicio extends javax.swing.JPanel {

    /**
     * Creates new form panelInicio
     */
    public PanelInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hacerPedido = new javax.swing.JButton();
        configMesa = new javax.swing.JButton();
        imagenPedido = new javax.swing.JLabel();
        imagenConfiguracionMesa = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1080, 720));
        setLayout(null);

        hacerPedido.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        hacerPedido.setText("Hacer Pedido");
        hacerPedido.setMaximumSize(new java.awt.Dimension(550, 150));
        hacerPedido.setMinimumSize(new java.awt.Dimension(550, 150));
        hacerPedido.setPreferredSize(new java.awt.Dimension(550, 150));
        hacerPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hacerPedidoActionPerformed(evt);
            }
        });
        add(hacerPedido);
        hacerPedido.setBounds(331, 175, 550, 150);

        configMesa.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        configMesa.setText("Configurar Mesa");
        configMesa.setMaximumSize(new java.awt.Dimension(550, 150));
        configMesa.setMinimumSize(new java.awt.Dimension(550, 150));
        configMesa.setPreferredSize(new java.awt.Dimension(550, 150));
        configMesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                configMesaMouseClicked(evt);
            }
        });
        configMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configMesaActionPerformed(evt);
            }
        });
        add(configMesa);
        configMesa.setBounds(331, 425, 550, 150);

        imagenPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FramesCliente/imagenes/imagenPedido.png"))); // NOI18N
        add(imagenPedido);
        imagenPedido.setBounds(165, 199, 100, 100);

        imagenConfiguracionMesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FramesCliente/imagenes/imagenConfiguracionMesa.png"))); // NOI18N
        add(imagenConfiguracionMesa);
        imagenConfiguracionMesa.setBounds(132, 433, 157, 127);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FramesCliente/imagenes/fondo azul_1.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1080, 720);
    }// </editor-fold>//GEN-END:initComponents

    private void configMesaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configMesaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_configMesaMouseClicked

    private void configMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configMesaActionPerformed
        // TODO add your handling code here:
        PanelMesa p = new PanelMesa();
        p.setSize(1080, 720);
        p.setLocation(0, 0);

        this.removeAll();
        this.add(p, BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_configMesaActionPerformed

    private void hacerPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hacerPedidoActionPerformed
        // TODO add your handling code here:
		PanelPedido p = new PanelPedido();
        p.setSize(1080, 720);
        p.setLocation(0, 0);

        this.removeAll();
        this.add(p, BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_hacerPedidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton configMesa;
    private javax.swing.JButton hacerPedido;
    private javax.swing.JLabel imagenConfiguracionMesa;
    private javax.swing.JLabel imagenPedido;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
