/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FramesCliente;

import java.awt.BorderLayout;
import javax.swing.JRadioButton;

/**
 *
 * @author Alber
 */
public class panelSelec2 extends javax.swing.JPanel {

    /**
     * Creates new form panelSelec2
     */
    public panelSelec2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollSelec2 = new javax.swing.JScrollPane();
        labelTitulo = new javax.swing.JLabel();
        botonPasarPostre = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1080, 720));
        setLayout(null);

        scrollSelec2.setPreferredSize(new java.awt.Dimension(1080, 500));
        add(scrollSelec2);
        scrollSelec2.setBounds(0, 96, 1080, 500);

        labelTitulo.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        labelTitulo.setText("Selección segundo plato");
        add(labelTitulo);
        labelTitulo.setBounds(299, 22, 482, 56);

        botonPasarPostre.setText("Pasar a postre");
        botonPasarPostre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPasarPostreActionPerformed(evt);
            }
        });
        add(botonPasarPostre);
        botonPasarPostre.setBounds(400, 600, 368, 70);

        botonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FramesCliente/imagenes/Volver.png"))); // NOI18N
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        add(botonVolver);
        botonVolver.setBounds(30, 600, 100, 70);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FramesCliente/imagenes/fondo azul_1.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1080, 720);
    }// </editor-fold>//GEN-END:initComponents

    private void botonPasarPostreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPasarPostreActionPerformed
        // TODO add your handling code here:
        FramePrincipal.setSegundo(obtenerSegundo());
        panelPostre p = new panelPostre();
        p.setSize(1080, 720);
        p.setLocation(0, 0);

        this.removeAll();
        this.add(p, BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_botonPasarPostreActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        // TODO add your handling code here:
        panelSelec1 p = new panelSelec1();
        p.setSize(1080, 720);
        p.setLocation(0, 0);

        this.removeAll();
        this.add(p, BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_botonVolverActionPerformed

    private String obtenerSegundo(){
        String primerPlato= "Filete con Patatas";
        //JRadioButton obj = (JRadioButton) seleccionSegundo.getSelection();
        //primerPlato= obj.getText();
        return primerPlato;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonPasarPostre;
    private javax.swing.JButton botonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JScrollPane scrollSelec2;
    // End of variables declaration//GEN-END:variables
}
