/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package FramesCliente;

import java.awt.BorderLayout;

/**
 *
 * @author bm0547
 */
public class PanelPedido extends javax.swing.JPanel {

	/**
	 * Creates new form PanelPedido
	 */
	public PanelPedido() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonCartaAbierta = new javax.swing.JButton();
        botonMenuCerrado = new javax.swing.JButton();
        botonInfo = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1080, 720));
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setLayout(null);

        botonCartaAbierta.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonCartaAbierta.setText("Carta Abierta");
        botonCartaAbierta.setMaximumSize(new java.awt.Dimension(550, 150));
        botonCartaAbierta.setMinimumSize(new java.awt.Dimension(550, 150));
        botonCartaAbierta.setPreferredSize(new java.awt.Dimension(550, 150));
        botonCartaAbierta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCartaAbiertaActionPerformed(evt);
            }
        });
        add(botonCartaAbierta);
        botonCartaAbierta.setBounds(265, 175, 550, 150);

        botonMenuCerrado.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonMenuCerrado.setText("Menús Cerrados");
        botonMenuCerrado.setMaximumSize(new java.awt.Dimension(550, 150));
        botonMenuCerrado.setMinimumSize(new java.awt.Dimension(550, 150));
        botonMenuCerrado.setPreferredSize(new java.awt.Dimension(550, 150));
        botonMenuCerrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMenuCerradoActionPerformed(evt);
            }
        });
        add(botonMenuCerrado);
        botonMenuCerrado.setBounds(265, 425, 550, 150);

        botonInfo.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FramesCliente/imagenes/configuracionMesa/imagenInformacion.png"))); // NOI18N
        botonInfo.setMaximumSize(new java.awt.Dimension(100, 100));
        botonInfo.setMinimumSize(new java.awt.Dimension(100, 100));
        botonInfo.setPreferredSize(new java.awt.Dimension(100, 100));
        botonInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInfoActionPerformed(evt);
            }
        });
        add(botonInfo);
        botonInfo.setBounds(30, 30, 100, 100);

        botonVolver.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        botonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FramesCliente/imagenes/Volver.png"))); // NOI18N
        botonVolver.setMaximumSize(new java.awt.Dimension(100, 75));
        botonVolver.setMinimumSize(new java.awt.Dimension(100, 75));
        botonVolver.setPreferredSize(new java.awt.Dimension(100, 75));
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        add(botonVolver);
        botonVolver.setBounds(30, 600, 100, 70);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FramesCliente/imagenes/fondo azul_1.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1080, 720);
    }// </editor-fold>//GEN-END:initComponents

    private void botonCartaAbiertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCartaAbiertaActionPerformed
        // TODO add your handling code here:
        panelSelec1 p = new panelSelec1();
        p.setSize(1080, 720);
        p.setLocation(0, 0);

        this.removeAll();
        this.add(p, BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_botonCartaAbiertaActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        // TODO add your handling code here:
		PanelInicio p = new PanelInicio();
		p.setSize(1080, 720);
		p.setLocation(0, 0);
		
		this.removeAll();
		this.add(p, BorderLayout.CENTER);
		this.revalidate();
		this.repaint();
    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInfoActionPerformed
        // TODO add your handling code here:
        FrameInformacion f = new FrameInformacion();
        f.setSize(700, 360);
        f.setLocation(175, 100);
        f.setVisible(true);
    }//GEN-LAST:event_botonInfoActionPerformed

    private void botonMenuCerradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMenuCerradoActionPerformed
        // TODO add your handling code here:
		PanelMenusCerrados p = new PanelMenusCerrados();
		p.setSize(1080, 720);
		p.setLocation(0, 0);
		
		this.removeAll();
		this.add(p, BorderLayout.CENTER);
		this.revalidate();
		this.repaint();
    }//GEN-LAST:event_botonMenuCerradoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCartaAbierta;
    private javax.swing.JButton botonInfo;
    private javax.swing.JButton botonMenuCerrado;
    private javax.swing.JButton botonVolver;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
