/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package FramesCliente;

import java.awt.BorderLayout;

/**
 *
 * @author bm0547
 */
public class PanelPedido extends javax.swing.JPanel {

	/**
	 * Creates new form PanelPedido
	 */
	public PanelPedido() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonCartaAbierta = new javax.swing.JButton();
        botonMenuCerrado = new javax.swing.JButton();
        botonInfo = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1080, 720));
        setMinimumSize(new java.awt.Dimension(1080, 720));

        botonCartaAbierta.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonCartaAbierta.setText("Carta Abierta");
        botonCartaAbierta.setMaximumSize(new java.awt.Dimension(550, 150));
        botonCartaAbierta.setMinimumSize(new java.awt.Dimension(550, 150));
        botonCartaAbierta.setPreferredSize(new java.awt.Dimension(550, 150));
        botonCartaAbierta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCartaAbiertaActionPerformed(evt);
            }
        });

        botonMenuCerrado.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonMenuCerrado.setText("Menús Cerrados");
        botonMenuCerrado.setMaximumSize(new java.awt.Dimension(550, 150));
        botonMenuCerrado.setMinimumSize(new java.awt.Dimension(550, 150));
        botonMenuCerrado.setPreferredSize(new java.awt.Dimension(550, 150));
        botonMenuCerrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMenuCerradoActionPerformed(evt);
            }
        });

        botonInfo.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonInfo.setText("i");
        botonInfo.setMaximumSize(new java.awt.Dimension(100, 100));
        botonInfo.setMinimumSize(new java.awt.Dimension(100, 100));
        botonInfo.setPreferredSize(new java.awt.Dimension(100, 100));
        botonInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInfoActionPerformed(evt);
            }
        });

        botonVolver.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        botonVolver.setText("Volver");
        botonVolver.setMaximumSize(new java.awt.Dimension(100, 75));
        botonVolver.setMinimumSize(new java.awt.Dimension(100, 75));
        botonVolver.setPreferredSize(new java.awt.Dimension(100, 75));
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonMenuCerrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonCartaAbierta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(265, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(botonInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(botonCartaAbierta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(botonMenuCerrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonCartaAbiertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCartaAbiertaActionPerformed
        // TODO add your handling code here:
        panelSelec1 p = new panelSelec1();
        p.setSize(1080, 720);
        p.setLocation(0, 0);

        this.removeAll();
        this.add(p, BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_botonCartaAbiertaActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        // TODO add your handling code here:
		PanelInicio p = new PanelInicio();
		p.setSize(1080, 720);
		p.setLocation(0, 0);
		
		this.removeAll();
		this.add(p, BorderLayout.CENTER);
		this.revalidate();
		this.repaint();
    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInfoActionPerformed
        // TODO add your handling code here:
		PanelInformacion p = new PanelInformacion();
		p.setSize(790, 350);
		p.setLocation(148, 30);
		
		this.add(p, BorderLayout.CENTER);
		this.revalidate();
		this.repaint();
    }//GEN-LAST:event_botonInfoActionPerformed

    private void botonMenuCerradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMenuCerradoActionPerformed
        // TODO add your handling code here:
		PanelMenusCerrados p = new PanelMenusCerrados();
		p.setSize(1080, 720);
		p.setLocation(0, 0);
		
		this.removeAll();
		this.add(p, BorderLayout.CENTER);
		this.revalidate();
		this.repaint();
    }//GEN-LAST:event_botonMenuCerradoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCartaAbierta;
    private javax.swing.JButton botonInfo;
    private javax.swing.JButton botonMenuCerrado;
    private javax.swing.JButton botonVolver;
    // End of variables declaration//GEN-END:variables
}
