/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FramesCliente;

import java.awt.BorderLayout;

/**
 *
 * @author Manu
 */
public class PanelSobremesa extends javax.swing.JPanel {

    /**
     * Creates new form PnaleSobremesa
     */
    public PanelSobremesa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonCafe = new javax.swing.JButton();
        botonPagar = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();
        imagenPedido = new javax.swing.JLabel();
        imagenCuenta = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1080, 720));
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setLayout(null);

        botonCafe.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonCafe.setText(" Pedir Café");
        botonCafe.setMaximumSize(new java.awt.Dimension(550, 150));
        botonCafe.setMinimumSize(new java.awt.Dimension(550, 150));
        botonCafe.setPreferredSize(new java.awt.Dimension(550, 150));
        botonCafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCafeActionPerformed(evt);
            }
        });
        add(botonCafe);
        botonCafe.setBounds(330, 170, 550, 150);

        botonPagar.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonPagar.setText("Solicitar la Cuenta");
        botonPagar.setMaximumSize(new java.awt.Dimension(550, 150));
        botonPagar.setMinimumSize(new java.awt.Dimension(550, 150));
        botonPagar.setPreferredSize(new java.awt.Dimension(550, 150));
        botonPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPagarActionPerformed(evt);
            }
        });
        add(botonPagar);
        botonPagar.setBounds(330, 430, 550, 150);

        botonVolver.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        botonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FramesCliente/imagenes/Volver.png"))); // NOI18N
        botonVolver.setMaximumSize(new java.awt.Dimension(100, 75));
        botonVolver.setMinimumSize(new java.awt.Dimension(100, 75));
        botonVolver.setPreferredSize(new java.awt.Dimension(100, 75));
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        add(botonVolver);
        botonVolver.setBounds(30, 600, 100, 70);

        imagenPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FramesCliente/imagenes/imagenCafeGrande.png"))); // NOI18N
        add(imagenPedido);
        imagenPedido.setBounds(165, 199, 100, 100);

        imagenCuenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagenCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FramesCliente/imagenes/imagenRecibo.png"))); // NOI18N
        add(imagenCuenta);
        imagenCuenta.setBounds(170, 460, 100, 100);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FramesCliente/imagenes/fondo azul_1.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1080, 720);
    }// </editor-fold>//GEN-END:initComponents

    private void botonPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPagarActionPerformed
        // TODO add your handling code here:
        panelCuenta p = new panelCuenta();
        p.setSize(1080, 720);
	p.setLocation(0, 0);
		
	this.removeAll();
	this.add(p, BorderLayout.CENTER);
	this.revalidate();
	this.repaint();
    }//GEN-LAST:event_botonPagarActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        // TODO add your handling code here:
        PanelMesa p = new PanelMesa();
        p.setSize(1080, 720);
	p.setLocation(0, 0);
		
	this.removeAll();
	this.add(p, BorderLayout.CENTER);
	this.revalidate();
	this.repaint();
    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonCafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCafeActionPerformed
        // TODO add your handling code here:
        FramePrincipal.setCafe(true);
        FrameCafe f = new FrameCafe();
        f.setSize(450, 200);
        f.setLocation(345, 200);
        f.setVisible(true);
    }//GEN-LAST:event_botonCafeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCafe;
    private javax.swing.JButton botonPagar;
    private javax.swing.JButton botonVolver;
    private javax.swing.JLabel imagenCuenta;
    private javax.swing.JLabel imagenPedido;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
