/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FramesCliente;

import java.awt.BorderLayout;

/**
 *
 * @author Alber
 */
public class panelPostre extends javax.swing.JPanel {

    /**
     * Creates new form panelPostre
     */
    public panelPostre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seleccionPostre = new javax.swing.ButtonGroup();
        labelTitulo = new javax.swing.JLabel();
        botonVolver = new javax.swing.JButton();
        botonConfirmarPedido = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton7 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1080, 720));
        setLayout(null);

        labelTitulo.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        labelTitulo.setText("Selección postre");
        add(labelTitulo);
        labelTitulo.setBounds(328, 11, 327, 56);

        botonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FramesCliente/imagenes/Volver.png"))); // NOI18N
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        add(botonVolver);
        botonVolver.setBounds(30, 600, 100, 70);

        botonConfirmarPedido.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonConfirmarPedido.setText("Confirmar Pedido");
        botonConfirmarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConfirmarPedidoActionPerformed(evt);
            }
        });
        add(botonConfirmarPedido);
        botonConfirmarPedido.setBounds(402, 613, 311, 51);

        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(50, 23));
        jLabel1.setMinimumSize(new java.awt.Dimension(50, 23));
        jLabel1.setPreferredSize(new java.awt.Dimension(50, 23));
        add(jLabel1);
        jLabel1.setBounds(548, 161, 50, 23);

        seleccionPostre.add(jRadioButton1);
        jRadioButton1.setText("Tarta de queso");
        jRadioButton1.setMaximumSize(new java.awt.Dimension(105, 30));
        jRadioButton1.setMinimumSize(new java.awt.Dimension(105, 30));
        jRadioButton1.setPreferredSize(new java.awt.Dimension(105, 30));
        add(jRadioButton1);
        jRadioButton1.setBounds(75, 157, 105, 30);

        seleccionPostre.add(jRadioButton2);
        jRadioButton2.setText("Helado de chocolate");
        jRadioButton2.setMaximumSize(new java.awt.Dimension(150, 30));
        jRadioButton2.setMinimumSize(new java.awt.Dimension(150, 30));
        jRadioButton2.setPreferredSize(new java.awt.Dimension(150, 30));
        add(jRadioButton2);
        jRadioButton2.setBounds(75, 210, 150, 30);

        seleccionPostre.add(jRadioButton3);
        jRadioButton3.setText("Helado de vainilla");
        jRadioButton3.setMaximumSize(new java.awt.Dimension(130, 30));
        jRadioButton3.setMinimumSize(new java.awt.Dimension(130, 30));
        jRadioButton3.setPreferredSize(new java.awt.Dimension(130, 30));
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        add(jRadioButton3);
        jRadioButton3.setBounds(75, 263, 130, 30);

        seleccionPostre.add(jRadioButton4);
        jRadioButton4.setText("Flan de huevo");
        jRadioButton4.setMaximumSize(new java.awt.Dimension(130, 30));
        jRadioButton4.setMinimumSize(new java.awt.Dimension(130, 30));
        jRadioButton4.setPreferredSize(new java.awt.Dimension(130, 30));
        add(jRadioButton4);
        jRadioButton4.setBounds(75, 316, 130, 30);

        seleccionPostre.add(jRadioButton5);
        jRadioButton5.setText("Crema Catalana");
        jRadioButton5.setMaximumSize(new java.awt.Dimension(130, 30));
        jRadioButton5.setMinimumSize(new java.awt.Dimension(130, 30));
        jRadioButton5.setPreferredSize(new java.awt.Dimension(130, 30));
        add(jRadioButton5);
        jRadioButton5.setBounds(75, 369, 130, 30);

        jLabel2.setText("jLabel2");
        jLabel2.setMaximumSize(new java.awt.Dimension(50, 23));
        jLabel2.setMinimumSize(new java.awt.Dimension(50, 23));
        jLabel2.setPreferredSize(new java.awt.Dimension(50, 23));
        add(jLabel2);
        jLabel2.setBounds(548, 214, 50, 23);

        jLabel3.setText("jLabel3");
        jLabel3.setMaximumSize(new java.awt.Dimension(50, 23));
        jLabel3.setMinimumSize(new java.awt.Dimension(50, 23));
        jLabel3.setPreferredSize(new java.awt.Dimension(50, 23));
        add(jLabel3);
        jLabel3.setBounds(548, 267, 50, 23);

        jLabel4.setText("jLabel4");
        jLabel4.setMaximumSize(new java.awt.Dimension(50, 23));
        jLabel4.setMinimumSize(new java.awt.Dimension(50, 23));
        jLabel4.setPreferredSize(new java.awt.Dimension(50, 23));
        add(jLabel4);
        jLabel4.setBounds(548, 320, 50, 23);

        jLabel5.setText("jLabel5");
        jLabel5.setMaximumSize(new java.awt.Dimension(50, 23));
        jLabel5.setMinimumSize(new java.awt.Dimension(50, 23));
        jLabel5.setPreferredSize(new java.awt.Dimension(50, 23));
        add(jLabel5);
        jLabel5.setBounds(548, 373, 50, 23);

        seleccionPostre.add(jRadioButton6);
        jRadioButton6.setText("Tarta de chocolate");
        jRadioButton6.setMaximumSize(new java.awt.Dimension(130, 30));
        jRadioButton6.setMinimumSize(new java.awt.Dimension(130, 30));
        jRadioButton6.setPreferredSize(new java.awt.Dimension(130, 30));
        add(jRadioButton6);
        jRadioButton6.setBounds(75, 422, 130, 30);

        jLabel6.setText("jLabel6");
        jLabel6.setMaximumSize(new java.awt.Dimension(50, 23));
        jLabel6.setMinimumSize(new java.awt.Dimension(50, 23));
        jLabel6.setPreferredSize(new java.awt.Dimension(50, 23));
        add(jLabel6);
        jLabel6.setBounds(548, 426, 50, 23);

        jLabel7.setText("jLabel7");
        jLabel7.setMaximumSize(new java.awt.Dimension(50, 23));
        jLabel7.setMinimumSize(new java.awt.Dimension(50, 23));
        jLabel7.setPreferredSize(new java.awt.Dimension(50, 23));
        add(jLabel7);
        jLabel7.setBounds(548, 479, 50, 23);

        seleccionPostre.add(jRadioButton7);
        jRadioButton7.setText("Tiramisú");
        jRadioButton7.setMaximumSize(new java.awt.Dimension(130, 30));
        jRadioButton7.setMinimumSize(new java.awt.Dimension(130, 30));
        jRadioButton7.setPreferredSize(new java.awt.Dimension(130, 30));
        add(jRadioButton7);
        jRadioButton7.setBounds(75, 475, 130, 30);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FramesCliente/imagenes/fondo azul_1.jpg"))); // NOI18N
        add(jLabel8);
        jLabel8.setBounds(0, 0, 1080, 720);
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        // TODO add your handling code here:
        panelSelec2 p = new panelSelec2();
        p.setSize(1080, 720);
        p.setLocation(0, 0);

        this.removeAll();
        this.add(p, BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonConfirmarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfirmarPedidoActionPerformed
        // TODO add your handling code here:
        FramePrincipal.setPostre(obtenerPostre());
        FramePrincipal.setMenu(false);
        FramePrincipal.setPlato(1);
        PanelMesa p = new PanelMesa();
        p.setSize(1080, 720);
        p.setLocation(0, 0);

        this.removeAll();
        this.add(p, BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_botonConfirmarPedidoActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private String obtenerPostre(){
        String postre;
        postre = seleccionPostre.getSelection().getActionCommand();
        return postre;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConfirmarPedido;
    private javax.swing.JButton botonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.ButtonGroup seleccionPostre;
    // End of variables declaration//GEN-END:variables
}
