/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FramesCliente;

import java.awt.BorderLayout;

/**
 *
 * @author Alber
 */
public class panelInicio extends javax.swing.JPanel {

    /**
     * Creates new form panelInicio
     */
    public panelInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hacerPedido = new javax.swing.JButton();
        configMesa = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1080, 720));

        hacerPedido.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        hacerPedido.setText("Hacer Pedido");

        configMesa.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        configMesa.setText("Configurar Mesa");
        configMesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                configMesaMouseClicked(evt);
            }
        });
        configMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configMesaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hacerPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(configMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(270, 270, 270))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(hacerPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(configMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void configMesaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configMesaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_configMesaMouseClicked

    private void configMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configMesaActionPerformed
        // TODO add your handling code here:
        PanelMesa p1 = new PanelMesa();
        p1.setSize(1080, 720);
        p1.setLocation(5, 5);

        this.removeAll();
        this.add(p1, BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_configMesaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton configMesa;
    private javax.swing.JButton hacerPedido;
    // End of variables declaration//GEN-END:variables
}
